// ---------------------------------------------------------------------------
// Stock Out List — mock data (feature-layer copy)
// Source of truth: src/lib/product-data/stockout-list.tsx
// Note: StockOutItem here uses the normalized inventory.types shape.
//       The render functions in stockOutColumns reference the original
//       StockOutItem fields from the source file — kept verbatim for
//       backward compat with any consumers of this mock.
// ---------------------------------------------------------------------------

import type { StockOutItem } from '@/features/inventory/types/inventory.types';
import type { ColumnDef } from '@/components/ui/tables/ReusableTable.types';

// Re-export status literal types for consumers that relied on the originals
export type StockOutStatus = 'Issued' | 'Pending' | 'Received';

export const stockOutColumns: ColumnDef<StockOutItem>[] = [
  {
    key: 'lcNo',
    label: 'LC No',
    cellClassName:
      'whitespace-nowrap px-5 py-2 text-sm text-slate-950 group-hover:text-white font-medium',
  },
  {
    key: 'poNo',
    label: 'PO No',
    cellClassName:
      'whitespace-nowrap px-5 py-2 text-sm text-slate-950 group-hover:text-white font-medium',
  },
  {
    key: 'buyer',
    label: 'Buyer',
  },
  {
    key: 'toLocation',
    label: 'Destination',
  },
  {
    key: 'createdBy',
    label: 'Created By',
  },
  {
    key: 'stockOutDate',
    label: 'Stock Out Date',
  },
  {
    key: 'productCount',
    label: 'Products',
  },
  {
    key: 'status',
    label: 'Status',
    render: (row) => {
      if (row.status === 'Issued') {
        return (
          <span className="inline-block min-w-[72px] text-center rounded-md bg-[#059669] px-3 py-1 text-xs font-medium text-white shadow-xs">
            Issued
          </span>
        );
      }
      if (row.status === 'Pending') {
        return (
          <span className="inline-block min-w-[72px] text-center rounded-md bg-[#eab308] px-3 py-1 text-xs font-medium text-white shadow-xs">
            Pending
          </span>
        );
      }
      return (
        <span className="inline-block min-w-[72px] text-center rounded-md bg-[#3b66c4] px-3 py-1 text-xs font-medium text-white shadow-xs">
          Received
        </span>
      );
    },
  },
];

/**
 * Normalized stock-out records mapped to the StockOutItem interface shape.
 * Original source fields: destination → toLocation, reqDate → stockOutDate,
 * products → productCount. totalQty defaults to 0 (not tracked in original data).
 * reqCreatedBy → createdBy.
 */
export const stockOutMockData: StockOutItem[] = [
  {
    id: 34,
    lcNo: '400',
    poNo: '500',
    buyer: 'APEX',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Issued',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 33,
    lcNo: '24524525',
    poNo: '4562345',
    buyer: 'APEX',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Issued',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 32,
    lcNo: 'Lc1111',
    poNo: 'Po111',
    buyer: 'APEX',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Pending',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 31,
    lcNo: '2435242',
    poNo: '24352345',
    buyer: 'MAF',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Pending',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 30,
    lcNo: '400',
    poNo: '500',
    buyer: 'APEX',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Pending',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 29,
    lcNo: '33',
    poNo: '55',
    buyer: 'Alex Smith',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Pending',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 28,
    lcNo: '400',
    poNo: '500',
    buyer: 'APEX',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Pending',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 27,
    lcNo: '400',
    poNo: '500',
    buyer: 'APEX',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Pending',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 26,
    lcNo: '400',
    poNo: '500',
    buyer: 'APEX',
    toLocation: '-',
    stockOutDate: '08-09-26',
    status: 'Pending',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 25,
    lcNo: 'Replacement',
    poNo: 'Replacement',
    buyer: 'MAF',
    toLocation: '-',
    stockOutDate: '02-09-26',
    status: 'Received',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 24,
    lcNo: '2',
    poNo: '200',
    buyer: 'POU HUNG',
    toLocation: '-',
    stockOutDate: '01-09-26',
    status: 'Received',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 23,
    lcNo: '1',
    poNo: '100',
    buyer: 'Alex Smith',
    toLocation: '-',
    stockOutDate: '01-09-26',
    status: 'Received',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 22,
    lcNo: '45245456',
    poNo: '4645645',
    buyer: 'POU HUNG',
    toLocation: '-',
    stockOutDate: '01-09-26',
    status: 'Received',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 21,
    lcNo: '2435242',
    poNo: '3453455',
    buyer: 'MAF',
    toLocation: '-',
    stockOutDate: '31-08-26',
    status: 'Received',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 20,
    lcNo: '2342',
    poNo: '2345234',
    buyer: 'POU HUNG',
    toLocation: '-',
    stockOutDate: '29-08-26',
    status: 'Issued',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 19,
    lcNo: 'Lc0123456',
    poNo: 'PO3472972',
    buyer: 'POU HUNG',
    toLocation: '-',
    stockOutDate: '22-08-26',
    status: 'Received',
    productCount: 2,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 18,
    lcNo: 'Lc0123456',
    poNo: 'PO3472972',
    buyer: 'POU HUNG',
    toLocation: '-',
    stockOutDate: '22-08-26',
    status: 'Received',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 17,
    lcNo: 'LC-2026-901',
    poNo: 'PO-77123',
    buyer: 'APEX',
    toLocation: 'Warehouse North',
    stockOutDate: '20-08-26',
    status: 'Issued',
    productCount: 5,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 16,
    lcNo: 'LC-2026-902',
    poNo: 'PO-77124',
    buyer: 'MAF',
    toLocation: 'Central Hub',
    stockOutDate: '18-08-26',
    status: 'Pending',
    productCount: 8,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 15,
    lcNo: 'LC-2026-880',
    poNo: 'PO-66230',
    buyer: 'Alex Smith',
    toLocation: 'Export Dock 3',
    stockOutDate: '15-08-26',
    status: 'Received',
    productCount: 12,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 14,
    lcNo: 'LC-2026-875',
    poNo: 'PO-66215',
    buyer: 'POU HUNG',
    toLocation: 'Retail Outlet 1',
    stockOutDate: '12-08-26',
    status: 'Issued',
    productCount: 6,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 13,
    lcNo: 'LC-2026-870',
    poNo: 'PO-66200',
    buyer: 'APEX',
    toLocation: '-',
    stockOutDate: '10-08-26',
    status: 'Pending',
    productCount: 4,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 12,
    lcNo: 'LC-2026-850',
    poNo: 'PO-55100',
    buyer: 'MAF',
    toLocation: 'Warehouse North',
    stockOutDate: '05-08-26',
    status: 'Received',
    productCount: 15,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 11,
    lcNo: 'LC-2026-840',
    poNo: 'PO-55080',
    buyer: 'POU HUNG',
    toLocation: 'Client Center',
    stockOutDate: '01-08-26',
    status: 'Issued',
    productCount: 9,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 10,
    lcNo: 'LC-2026-830',
    poNo: 'PO-55060',
    buyer: 'Alex Smith',
    toLocation: '-',
    stockOutDate: '28-07-26',
    status: 'Pending',
    productCount: 3,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 9,
    lcNo: 'LC-2026-820',
    poNo: 'PO-44020',
    buyer: 'APEX',
    toLocation: 'Central Hub',
    stockOutDate: '25-07-26',
    status: 'Received',
    productCount: 11,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 8,
    lcNo: 'LC-2026-810',
    poNo: 'PO-44010',
    buyer: 'MAF',
    toLocation: 'Warehouse North',
    stockOutDate: '20-07-26',
    status: 'Issued',
    productCount: 8,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 7,
    lcNo: 'LC-2026-800',
    poNo: 'PO-44000',
    buyer: 'POU HUNG',
    toLocation: '-',
    stockOutDate: '15-07-26',
    status: 'Pending',
    productCount: 6,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 6,
    lcNo: 'LC-2026-790',
    poNo: 'PO-33090',
    buyer: 'APEX',
    toLocation: 'Export Dock 3',
    stockOutDate: '10-07-26',
    status: 'Received',
    productCount: 14,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 5,
    lcNo: 'LC-2026-780',
    poNo: 'PO-33080',
    buyer: 'Alex Smith',
    toLocation: 'Client Center',
    stockOutDate: '05-07-26',
    status: 'Issued',
    productCount: 7,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 4,
    lcNo: 'LC-2026-770',
    poNo: 'PO-33070',
    buyer: 'MAF',
    toLocation: '-',
    stockOutDate: '01-07-26',
    status: 'Pending',
    productCount: 5,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 3,
    lcNo: 'LC-2026-760',
    poNo: 'PO-22050',
    buyer: 'POU HUNG',
    toLocation: 'Central Hub',
    stockOutDate: '25-06-26',
    status: 'Received',
    productCount: 10,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
  {
    id: 2,
    lcNo: 'LC-2026-750',
    poNo: 'PO-22040',
    buyer: 'APEX',
    toLocation: 'Warehouse North',
    stockOutDate: '20-06-26',
    status: 'Issued',
    productCount: 8,
    totalQty: 0,
    createdBy: 'Tashdik',
  },
  {
    id: 1,
    lcNo: 'LC-2026-740',
    poNo: 'PO-22030',
    buyer: 'Alex Smith',
    toLocation: 'Retail Outlet 1',
    stockOutDate: '15-06-26',
    status: 'Received',
    productCount: 12,
    totalQty: 0,
    createdBy: 'Super Admin',
  },
];
