// ---------------------------------------------------------------------------
// Batch Product List — mock data
// Seeded directly from warehouse inventory reports
// ---------------------------------------------------------------------------

import type { ColumnDef } from "@/components/tables/ReusableTable.types";

export interface BatchProductItem {
  id: number;
  productName: string;
  sku: string;
  material: string;
  category: string;
  subCategory: string;
  color: string;
  size: string;
  batchNo: string;
  received: number;
  issued: number;
  blocked: number;
  shipable: number;
  warehouse: string;
  zone: string;
  subZone: string;
  rack: string;
  ageDays: string;
  zoneChangeIn: string;
  createdAt: string;
}

export const batchProductColumns: ColumnDef<BatchProductItem>[] = [
  {
    key: "productName",
    label: "Product Name",
    cellClassName:
      "whitespace-nowrap px-5 py-2 text-sm font-semibold text-slate-950 group-hover:text-white",
  },
  {
    key: "sku",
    label: "SKU",
    render: (row) => (
      <span className="font-mono text-xs tracking-tight text-slate-600 group-hover:text-slate-100">
        {row.sku}
      </span>
    ),
  },
  {
    key: "material",
    label: "Material",
  },
  {
    key: "category",
    label: "Category",
    render: (row) => (
      <span className="inline-flex items-center rounded-md bg-slate-100 px-2 py-0.5 text-xs font-medium capitalize text-slate-700 group-hover:bg-white/20 group-hover:text-white">
        {row.category}
      </span>
    ),
  },
  {
    key: "subCategory",
    label: "Sub Category",
    render: (row) => <span className="capitalize">{row.subCategory}</span>,
  },
  {
    key: "color",
    label: "Color",
  },
  {
    key: "size",
    label: "Size",
  },
  {
    key: "batchNo",
    label: "Batch / Lot No",
    render: (row) => (
      <span className="inline-flex items-center rounded-md border border-indigo-200 bg-indigo-50 px-2.5 py-0.5 font-mono text-xs font-medium text-indigo-700 group-hover:border-white/30 group-hover:bg-white/20 group-hover:text-white">
        {row.batchNo}
      </span>
    ),
  },
  {
    key: "received",
    label: "Received",
    headerClassName:
      "whitespace-nowrap border-b border-slate-100 px-5 py-2 text-right text-xs font-bold text-slate-900",
    cellClassName:
      "whitespace-nowrap px-5 py-2 text-right text-sm text-slate-950 group-hover:text-white font-medium tabular-nums",
    render: (row) => row.received.toLocaleString(),
  },
  {
    key: "issued",
    label: "Issued",
    headerClassName:
      "whitespace-nowrap border-b border-slate-100 px-5 py-2 text-right text-xs font-bold text-slate-900",
    cellClassName:
      "whitespace-nowrap px-5 py-2 text-right text-sm text-slate-950 group-hover:text-white tabular-nums",
    render: (row) => row.issued.toLocaleString(),
  },
  {
    key: "blocked",
    label: "Blocked",
    headerClassName:
      "whitespace-nowrap border-b border-slate-100 px-5 py-2 text-right text-xs font-bold text-slate-900",
    cellClassName:
      "whitespace-nowrap px-5 py-2 text-right text-sm text-slate-950 group-hover:text-white tabular-nums",
    render: (row) =>
      row.blocked > 0 ? (
        <span className="inline-block rounded-md bg-amber-50 px-2 py-0.5 text-xs font-semibold text-amber-700 group-hover:bg-amber-400 group-hover:text-slate-950">
          {row.blocked.toLocaleString()}
        </span>
      ) : (
        <span>0</span>
      ),
  },
  {
    key: "shipable",
    label: "Shipable",
    headerClassName:
      "whitespace-nowrap border-b border-slate-100 px-5 py-2 text-right text-xs font-bold text-slate-900",
    cellClassName:
      "whitespace-nowrap px-5 py-2 text-right text-sm text-slate-950 group-hover:text-white tabular-nums",
    render: (row) => row.shipable.toLocaleString(),
  },
  {
    key: "warehouse",
    label: "Warehouse",
  },
  {
    key: "zone",
    label: "Zone",
  },
  {
    key: "subZone",
    label: "Sub Zone",
  },
  {
    key: "rack",
    label: "Rack",
  },
  {
    key: "ageDays",
    label: "Age (Days)",
    render: (row) => (
      <span className="inline-flex rounded-full bg-slate-100 px-2.5 py-0.5 text-xs font-medium text-slate-700 group-hover:bg-white/20 group-hover:text-white">
        {row.ageDays}
      </span>
    ),
  },
  {
    key: "zoneChangeIn",
    label: "Zone Change In",
  },
  {
    key: "createdAt",
    label: "Created At",
  },
];

export const batchProductData: BatchProductItem[] = [
  {
    id: 271,
    productName: "TD Shirt 37 Silver lady",
    sku: "TD-SHIRT-CLOTH-37-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "37",
    batchNo: "B20260908-00041",
    received: 20,
    issued: 0,
    blocked: 20,
    shipable: 0,
    warehouse: "Mirpur2",
    zone: "Mirpur 1",
    subZone: "Solimuddin Market",
    rack: "Rack_1",
    ageDays: "0 Days",
    zoneChangeIn: "181 Days",
    createdAt: "08-09-2026",
  },
  {
    id: 270,
    productName: "TD Shirt 36 Silver lady",
    sku: "TD-SHIRT-CLOTH-36-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "36",
    batchNo: "B20260908-00041",
    received: 10,
    issued: 0,
    blocked: 10,
    shipable: 0,
    warehouse: "Gazipur",
    zone: "Tongi Zone",
    subZone: "College Gate",
    rack: "Rack 1",
    ageDays: "0 Days",
    zoneChangeIn: "181 Days",
    createdAt: "08-09-2026",
  },
  {
    id: 269,
    productName: "TD Shirt 40 Silver lady",
    sku: "TD-SHIRT-CLOTH-40-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "40",
    batchNo: "B20260908-00040",
    received: 50,
    issued: 0,
    blocked: 50,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack1",
    ageDays: "0 Days",
    zoneChangeIn: "181 Days",
    createdAt: "08-09-2026",
  },
  {
    id: 268,
    productName: "TD Shirt 39 Silver lady",
    sku: "TD-SHIRT-CLOTH-39-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "39",
    batchNo: "B20260908-00040",
    received: 40,
    issued: 0,
    blocked: 40,
    shipable: 0,
    warehouse: "Mirpur2",
    zone: "Mirpur 1",
    subZone: "Solimuddin Market",
    rack: "Rack_1",
    ageDays: "0 Days",
    zoneChangeIn: "181 Days",
    createdAt: "08-09-2026",
  },
  {
    id: 267,
    productName: "TD Shirt 38 Silver lady",
    sku: "TD-SHIRT-CLOTH-38-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "38",
    batchNo: "B20260908-00040",
    received: 30,
    issued: 11,
    blocked: 19,
    shipable: 0,
    warehouse: "Gazipur",
    zone: "Tongi Zone",
    subZone: "College Gate",
    rack: "Rack 2",
    ageDays: "0 Days",
    zoneChangeIn: "181 Days",
    createdAt: "08-09-2026",
  },
  {
    id: 266,
    productName: "TD Shirt 37 Silver lady",
    sku: "TD-SHIRT-CLOTH-37-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "37",
    batchNo: "B20260908-00040",
    received: 20,
    issued: 0,
    blocked: 20,
    shipable: 0,
    warehouse: "Mirpur2",
    zone: "Mirpur 1",
    subZone: "Solimuddin Market",
    rack: "Rack_1",
    ageDays: "0 Days",
    zoneChangeIn: "181 Days",
    createdAt: "08-09-2026",
  },
  {
    id: 265,
    productName: "TD Shirt 36 Silver lady",
    sku: "TD-SHIRT-CLOTH-36-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "36",
    batchNo: "B20260908-00040",
    received: 10,
    issued: 5,
    blocked: 5,
    shipable: 0,
    warehouse: "Mirpur2",
    zone: "Mirpur 1",
    subZone: "Solimuddin Market",
    rack: "Rack_1",
    ageDays: "0 Days",
    zoneChangeIn: "181 Days",
    createdAt: "08-09-2026",
  },
  {
    id: 264,
    productName: "test000 48 Silver male",
    sku: "TEST000-ELECTRONICS-48-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "48",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 0,
    blocked: 10000,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 263,
    productName: "test000 47 Silver male",
    sku: "TEST000-ELECTRONICS-47-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "47",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 0,
    blocked: 10000,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 262,
    productName: "test000 46 Silver male",
    sku: "TEST000-ELECTRONICS-46-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "46",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 0,
    blocked: 10000,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 261,
    productName: "test000 45 Silver male",
    sku: "TEST000-ELECTRONICS-45-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "45",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 500,
    blocked: 9500,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 260,
    productName: "test000 44 Silver male",
    sku: "TEST000-ELECTRONICS-44-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "44",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 5000,
    blocked: 5000,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 259,
    productName: "test000 43 Silver male",
    sku: "TEST000-ELECTRONICS-43-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "43",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 5000,
    blocked: 5000,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 258,
    productName: "test000 42 Silver male",
    sku: "TEST000-ELECTRONICS-42-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "42",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 500,
    blocked: 9500,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 257,
    productName: "test000 41 Silver male",
    sku: "TEST000-ELECTRONICS-41-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "41",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 5000,
    blocked: 5000,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 256,
    productName: "test000 40 Silver male",
    sku: "TEST000-ELECTRONICS-40-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "40",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 500,
    blocked: 9500,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 255,
    productName: "test000 39 Silver male",
    sku: "TEST000-ELECTRONICS-39-SILVER-MALE",
    material: "Aluminium + Plastic",
    category: "electronics",
    subCategory: "laptop",
    color: "Silver",
    size: "39",
    batchNo: "B20260902-00039",
    received: 10000,
    issued: 1000,
    blocked: 9000,
    shipable: 0,
    warehouse: "WarehouseFG",
    zone: "Zone1",
    subZone: "SubZone1",
    rack: "Rack2",
    ageDays: "6 Days",
    zoneChangeIn: "175 Days",
    createdAt: "02-09-2026",
  },
  {
    id: 254,
    productName: "TD Shirt 42 Silver lady",
    sku: "TD-SHIRT-CLOTH-42-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "42",
    batchNo: "B20260901-00038",
    received: 20,
    issued: 0,
    blocked: 20,
    shipable: 0,
    warehouse: "Mirpur2",
    zone: "Mirpur 1",
    subZone: "Solimuddin Market",
    rack: "Rack_1",
    ageDays: "7 Days",
    zoneChangeIn: "174 Days",
    createdAt: "01-09-2026",
  },
  {
    id: 253,
    productName: "TD Shirt 41 Silver lady",
    sku: "TD-SHIRT-CLOTH-41-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "41",
    batchNo: "B20260901-00038",
    received: 20,
    issued: 0,
    blocked: 20,
    shipable: 0,
    warehouse: "Mirpur2",
    zone: "Mirpur 1",
    subZone: "Solimuddin Market",
    rack: "Rack_1",
    ageDays: "7 Days",
    zoneChangeIn: "174 Days",
    createdAt: "01-09-2026",
  },
  {
    id: 252,
    productName: "TD Shirt 40 Silver lady",
    sku: "TD-SHIRT-CLOTH-40-SILVER-LADY",
    material: "Poly",
    category: "cloth",
    subCategory: "shirt",
    color: "Silver",
    size: "40",
    batchNo: "B20260901-00038",
    received: 20,
    issued: 0,
    blocked: 20,
    shipable: 0,
    warehouse: "Mirpur2",
    zone: "Mirpur 1",
    subZone: "Solimuddin Market",
    rack: "Rack_1",
    ageDays: "7 Days",
    zoneChangeIn: "174 Days",
    createdAt: "01-09-2026",
  },
];

