// ---------------------------------------------------------------------------
// Permission List — mock dataset
// Seeded directly from reference Page 1 & expanded to 4 pages (40 records)
// ---------------------------------------------------------------------------

import type { ColumnDef } from "@/components/tables/ReusableTable.types";

export interface PermissionRecord {
  id: number;
  moduleName: string;
  adjust: boolean;
  approve: boolean;
  challan: boolean;
  create: boolean;
  decide: boolean;
  delete: boolean;
  deliver: boolean;
  export: boolean;
  issue: boolean;
  manage: boolean;
  read: boolean;
  receive: boolean;
  reject: boolean;
  relocate: boolean;
  test: boolean;
  test234234: boolean;
  track: boolean;
  update: boolean;
  variant: boolean;
  watch: boolean;
}

const renderCheckOrDash = (active: boolean) => (
  <div className="flex items-center justify-center">
    {active ? (
      <span className="text-emerald-600 font-bold text-xs leading-none">✓</span>
    ) : (
      <span className="text-red-400 font-bold text-xs leading-none">-</span>
    )}
  </div>
);

export const permissionColumns: ColumnDef<PermissionRecord>[] = [
  {
    key: "moduleName",
    label: "Module Name",
    cellClassName: "whitespace-nowrap px-5 py-2.5 text-sm font-medium text-slate-900 group-hover:text-white text-left",
  },
  {
    key: "adjust",
    label: "Adjust",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.adjust),
  },
  {
    key: "approve",
    label: "Approve",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.approve),
  },
  {
    key: "challan",
    label: "Challan",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.challan),
  },
  {
    key: "create",
    label: "Create",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.create),
  },
  {
    key: "decide",
    label: "Decide",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.decide),
  },
  {
    key: "delete",
    label: "Delete",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.delete),
  },
  {
    key: "deliver",
    label: "Deliver",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.deliver),
  },
  {
    key: "export",
    label: "Export",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.export),
  },
  {
    key: "issue",
    label: "Issue",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.issue),
  },
  {
    key: "manage",
    label: "Manage",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.manage),
  },
  {
    key: "read",
    label: "Read",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.read),
  },
  {
    key: "receive",
    label: "Receive",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.receive),
  },
  {
    key: "reject",
    label: "Reject",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.reject),
  },
  {
    key: "relocate",
    label: "Relocate",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.relocate),
  },
  {
    key: "test",
    label: "Test",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.test),
  },
  {
    key: "test234234",
    label: "Test234234",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.test234234),
  },
  {
    key: "track",
    label: "Track",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.track),
  },
  {
    key: "update",
    label: "Update",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.update),
  },
  {
    key: "variant",
    label: "Variant",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.variant),
  },
  {
    key: "watch",
    label: "Watch",
    headerClassName: "whitespace-nowrap border-b border-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-900",
    cellClassName: "whitespace-nowrap px-3 py-2.5 text-center text-sm",
    render: (row) => renderCheckOrDash(row.watch),
  },
];

export const PERMISSION_DATA: PermissionRecord[] = [
  // ── Page 1 (Exact rows from reference screenshot) ──
  {
    id: 58,
    moduleName: "Xyx",
    adjust: true,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: false,
    issue: true,
    manage: false,
    read: false,
    receive: false,
    reject: false,
    relocate: false,
    test: true,
    test234234: true,
    track: false,
    update: false,
    variant: false,
    watch: false,
  },
  {
    id: 57,
    moduleName: "Requisition",
    adjust: false,
    approve: true,
    challan: true,
    create: true,
    decide: true,
    delete: true,
    deliver: true,
    export: false,
    issue: true,
    manage: true,
    read: true,
    receive: true,
    reject: true,
    relocate: false,
    test: true,
    test234234: false,
    track: true,
    update: true,
    variant: true,
    watch: true,
  },
  {
    id: 56,
    moduleName: "Test-2",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: false,
    issue: false,
    manage: false,
    read: false,
    receive: false,
    reject: false,
    relocate: false,
    test: true,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: false,
  },
  {
    id: 55,
    moduleName: "Test_td",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 54,
    moduleName: "Test",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: true,
    export: false,
    issue: true,
    manage: false,
    read: true,
    receive: true,
    reject: true,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 53,
    moduleName: "Setting",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: false,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 52,
    moduleName: "Notification",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: false,
  },
  {
    id: 51,
    moduleName: "Audit-Log",
    adjust: false,
    approve: true,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: true,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 50,
    moduleName: "Report",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 48,
    moduleName: "Monthly-Delivery",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },

  // ── Page 2 (Extended Modules) ──
  {
    id: 47,
    moduleName: "Weekly-Delivery",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 46,
    moduleName: "Delivery-Summary",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 45,
    moduleName: "Stock-In",
    adjust: true,
    approve: true,
    challan: true,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: true,
    issue: true,
    manage: true,
    read: true,
    receive: true,
    reject: true,
    relocate: true,
    test: false,
    test234234: false,
    track: true,
    update: true,
    variant: true,
    watch: true,
  },
  {
    id: 44,
    moduleName: "Stock-Out",
    adjust: true,
    approve: true,
    challan: true,
    create: true,
    decide: false,
    delete: true,
    deliver: true,
    export: true,
    issue: true,
    manage: true,
    read: true,
    receive: false,
    reject: true,
    relocate: false,
    test: false,
    test234234: false,
    track: true,
    update: true,
    variant: true,
    watch: true,
  },
  {
    id: 43,
    moduleName: "Stock-Out-List",
    adjust: false,
    approve: false,
    challan: true,
    create: false,
    decide: false,
    delete: true,
    deliver: true,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: true,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 42,
    moduleName: "Batch-List",
    adjust: true,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: true,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: true,
    test: false,
    test234234: false,
    track: true,
    update: true,
    variant: true,
    watch: true,
  },
  {
    id: 41,
    moduleName: "FG-Master-Stock",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 40,
    moduleName: "FG-Current-Stock",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 39,
    moduleName: "Location-Wise-Stock",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: true,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 38,
    moduleName: "Stock-Ledger",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: true,
    update: false,
    variant: false,
    watch: true,
  },

  // ── Page 3 (Extended Modules) ──
  {
    id: 37,
    moduleName: "Master-FG-Product",
    adjust: true,
    approve: true,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: true,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: true,
    watch: true,
  },
  {
    id: 36,
    moduleName: "Variant-FG-Product",
    adjust: true,
    approve: true,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: true,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: true,
    watch: true,
  },
  {
    id: 35,
    moduleName: "Category",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 34,
    moduleName: "Sub-Category",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 33,
    moduleName: "Material",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 32,
    moduleName: "Color",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 31,
    moduleName: "Warehouse",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: true,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 30,
    moduleName: "Zone",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: true,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 29,
    moduleName: "Sub-Zone",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: true,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 28,
    moduleName: "Rack",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: true,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },

  // ── Page 4 (Extended Modules) ──
  {
    id: 27,
    moduleName: "Buyer",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: true,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 26,
    moduleName: "Customer",
    adjust: false,
    approve: false,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: true,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 25,
    moduleName: "User",
    adjust: false,
    approve: true,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 24,
    moduleName: "Role",
    adjust: false,
    approve: true,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 23,
    moduleName: "Permission",
    adjust: false,
    approve: true,
    challan: false,
    create: true,
    decide: false,
    delete: true,
    deliver: false,
    export: false,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
  {
    id: 22,
    moduleName: "Stock-Aging-Green",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 21,
    moduleName: "Stock-Aging-Yellow",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 20,
    moduleName: "Stock-Aging-Red",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 19,
    moduleName: "Dashboard",
    adjust: false,
    approve: false,
    challan: false,
    create: false,
    decide: false,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: false,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: false,
    variant: false,
    watch: true,
  },
  {
    id: 18,
    moduleName: "System-Settings",
    adjust: true,
    approve: true,
    challan: false,
    create: true,
    decide: true,
    delete: false,
    deliver: false,
    export: true,
    issue: false,
    manage: true,
    read: true,
    receive: false,
    reject: false,
    relocate: false,
    test: false,
    test234234: false,
    track: false,
    update: true,
    variant: false,
    watch: true,
  },
];

export const permissionData: PermissionRecord[] = PERMISSION_DATA;
export default permissionData;

